- app/assets/javascripts/cart_items.coffee
- app/assets/javascripts/orders.coffee
- app/assets/stylesheets/cart_items.scss
- app/assets/stylesheets/orders.scss
- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/helpers/cart_items_helper.rb
- app/helpers/orders_helper.rb
- test/controllers/cart_items_controller_test.rb
- test/controllers/orders_controller_test.rb
cart-items,oders controllerを追加しました
> add controller

- app/controllers/musics_controller.rb
- app/controllers/products_controller.rb
products、musicsコントローラにアクションを追加しました
> add_action

- app/controllers/administrators_controller.rb
- app/controllers/users_controller.rb
下記の３つのコントローラーのアクションとビューファイルを全て追加しました
1. greeds
2. administrators
3. users
> add action and view

- app/models/music.rb
- app/models/product.rb
- db/migrate/20180710123837_create_products.rb
- db/migrate/20180710123935_create_musics.rb
- db/schema.rb
- test/fixtures/musics.yml
- test/fixtures/products.yml
- test/models/music_test.rb
- test/models/product_test.rb
モデルと、データベースへの追加
・productsテーブル
・musicテーブル
> add_products&musics

- app/controllers/products_controller.rb
- app/views/products/index.html.erb
- app/views/products/new.html.erb
追加view
・product new
・product index
> temporary_save

- app/views/greeds/index.html.erb
- db/migrate/20180711062853_create_greeds.rb
- db/schema.rb
geed_imageカラムの追加
greed indexのviewを追加
確認お願いします。
> f_add_greedimage

- app/controllers/users/registrations_controller.rb
- app/models/address.rb
- app/models/user.rb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- config/initializers/i18n.rb
- config/locales/devise.ja.yml
- db/migrate/20180712040509_change_columns_users.rb
- db/schema.rb
下記の変更を行いました。
1.ユーザーのsignupページの作成　（app/views/users/registrations/new.html.erb）
2.ユーザーのsignupページの日本語化
（config/initializers/i18n.rbとconfig/locales/devise.ja.ymlファイルの追加）
3.userテーブルからpostal_codeカラムの削除　（db/schema.rbの編集)
取り急ぎ3のpostal_codeがuserテーブルから消えているかの確認だけお願いします。
> T add view sign up

- app/controllers/cart_items_controller.rb
- app/views/cart_items/edit.html.erb
cart-items ざっくりhtml作成しました。
やりたいことが伝われば良いかなと。
指摘お願いします
> M_add_cart-items_html

- app/controllers/musics_controller.rb
- app/controllers/products_controller.rb
- app/models/music.rb
- app/models/product.rb
- app/views/products/new.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- db/schema.rb
追加 product view controller
・new
・show
> S addhtml product#2

- app/models/cart_item.rb
- app/models/greed.rb
- app/models/order.rb
- app/models/order_item.rb
- app/models/product.rb
- app/models/user.rb
- db/migrate/20180711065940_drop_address.rb
- db/migrate/20180713031906_create_order_items.rb
- db/schema.rb
- test/fixtures/order_items.yml
- test/models/order_item_test.rb
orderitemsモデルの作成
モデル間の関係性
確認をお願いします。
> F add orderitems model

- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/models/cart_item.rb
- app/views/cart_items/edit.html.erb
- app/views/cart_items/show.html.erb
- app/views/orders/thanks.html.erb
・cart-items(edit)
・cart-item(show)
・thanksページ
html変更しました。
> M add cart items html new

- app/assets/stylesheets/application.css
- app/controllers/administrators_controller.rb
- app/controllers/musics_controller.rb
- app/controllers/products_controller.rb
- app/views/administrators/index.html.erb
- app/views/administrators/new.html.erb
- app/views/products/edit.html.erb
- app/views/products/new.html.erb
- app/views/products/show.html.erb
- config/routes.rb
> F add product showedit

- app/controllers/cart_items_controller.rb
- app/controllers/musics_controller.rb
- app/controllers/products_controller.rb
- app/models/cart_item.rb
- app/models/greed.rb
- app/models/product.rb
- app/models/user.rb
- app/views/products/edit.html.erb
- app/views/products/index.html.erb
- app/views/products/new.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- db/schema.rb
変更点
・カートに追加ボタン周りの処理
一時的な変更
・greed-product、user-cart_itemのアソシエーション記述コメントアウト
（saveメソッドが動作しなかったため）
> addcart_method

- db/migrate/20180715035846_add_total_price_to_orders.rb
- db/schema.rb
・ordersテーブルにtotal_priceカラム追加しました。
> M_migrate_order

- app/controllers/addresses﻿_controller.rb
- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/views/users/registrations/new.html.erb
- config/locales/devise.ja.yml
signup pageにaddressテーブルの情報（郵便番号、住所）の欄を表示させるよう変更しました。
まだその二つだけ日本語化できていませんが、確認よろしくお願いします。
> modified signup view

- app/controllers/application_controller.rb
- app/views/administrators/registrations/new.html.erb
- app/views/administrators/sessions/new.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/sessions/new.html.erb
- app/views/users/shared/_links.html.erb
- db/schema.rb
ログイン、ログアウト後のリダイレクト先を設定しました。
一番上のapp/controllers/application_controller.rbのファイルのみ確認お願いします。
取り急ぎ、ユーザーと管理者共に
　ログイン後・・・greeds_index_path
　ログアウト後・・・ログイン画面
に遷移するように仮設定しています。
> add login logout後のリダイレクト先設定

- app/controllers/products_controller.rb
- app/views/products/category.html.erb
- config/routes.rb
並び替えの修正をしました。
ルートがずれていると思うので、修正します。
> f_modified_sort

- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/views/greeds/index.html.erb
- config/initializers/devise.rb
- config/routes.rb
- db/schema.rb
logoutできるようdevise周りを修正しました。
下記ファイルのみ確認お願いします。
app/controllers/application_controller.rb
> modified devise logout

- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/models/user.rb
- app/views/users/registrations/new.html.erb
下記の点を修正しました。確認お願いします。
　・新規登録ページにてアドレスモデルの情報が反映されない問題
確認して欲しいフォルダ
　app/controllers/application_controller.rb
解決方法
　application_controllerにて記載するconfigure_permitted_parametersの記載方法を変更
> modified signupでaddressのデータが入らない問題

- app/assets/javascripts/order.js
- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/cart_items/index.html.erb
- app/views/orders/new.html.erb
- config/initializers/assets.rb
- config/locales/ja.yml
- config/routes.rb
- db/migrate/20180711023006_create_orders.rb
- db/schema.rb
仮の決済処理機能です。未完成ですが取り急ぎプルリクします。
orderとorder_itemは生成できますが、いくつか注意点があります。
・支払い方法
をラジオボタンで選択するとエラー（支払い方法は保存できません）
・希望配達日を設定できない（空欄の場合、今日の日付＋3が格納されます）
・在庫数の反映ができない（product.saveでエラー）
・決済後のカートリセットはテストしてないので使えるか不明（コメントアウト中）
主な変更点
・ordersテーブルに total_price,postal_codeカラムを追加
・delivery_date,order_dateカラムの型の変更,order_datetimeに名前変更
　→delivery_dateは日付しか使わないため。
> S add order prossess

- Gemfile
- Gemfile.lock
- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/views/orders/new.html.erb
- app/views/orders/thanks.html.erb
> add_gem_pry

- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/cart_items/index.html.erb
- app/views/layouts/application.html.erb
- app/views/orders/new.html.erb
以下の問題を解決しました。
・数量0で決済画面に進めてしまう 
・他の人が買って在庫切れになった場合でも購入できてしまう
・支払い方法選択するとエラーが起こる (enum解除）
・住所を入力しなくても進める(userのdefault_addressをラジオボタンに初期入力）
残りの問題点
・希望配達日を選択するカレンダーが表示できない
> modify_cart-process

- app/controllers/application_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users_controller.rb
- app/views/users/edit.html.erb
- app/views/users/password_edit.html.erb
- app/views/users/passwords/edit.html.erb
- config/routes.rb
下記の点を変更しました。
・パスワード変更ページの追加
・パスワード変更機能の追加
備考（今後の参考までに）
deviseでもパスワード設定画面と機能がもともと備わっているのですが、どうしてもログアウト状態に一度なることやルーティングエラーを避けられなかったので、結局deviseを使用せずに機能を実装しました。
（下記のURLのSolutuion３を参考にしました。deviseの機能を生かす場合はSolution1,2となります。）
> T add change password

- Gemfile
- Gemfile.lock
- app/controllers/users_controller.rb
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- app/views/users/admin_index.html.erb
- config/initializers/kaminari_config.rb
- config/locales/kaminari_ja.yml
- db/schema.rb
> f_modified_table

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/orders/admin_show.html.erb
- app/views/orders/index.html.erb
- app/views/users/registrations/new.html.erb
- app/views/users/show.html.erb
- config/environments/development.rb
下記の点を変更しました、確認お願いします。
<変更点>
①管理者側　注文詳細画面で配送状況を変更できるように修正
②管理者側　注文一覧画面から注文詳細画面へ移動できるようリンクを修正
<対象ファイル>
①19  app/views/orders/admin_show.html.erb
②10  app/views/orders/index.html.erb
> modified AdminOrderShow

- app/controllers/orders_controller.rb
- app/controllers/products_controller.rb
- config/routes.rb
product関連の名前修正
admin_動作_対象
確認お願いします。
> f_modified_roots

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/products/admin_index.scss
- app/assets/stylesheets/products/admin_new.scss
- app/views/products/admin_category.html.erb
- app/views/products/admin_index.html.erb
- app/views/products/admin_new.html.erb
- app/views/products/show.html.erb
- app/views/users/admin_edit.html.erb
- app/views/users/admin_show.html.erb
- config/initializers/assets.rb
> f_design_new_product

- app/assets/stylesheets/orders/admin_index.scss
- app/assets/stylesheets/products/admin_index.scss
- app/views/orders/admin_index.html.erb
- app/views/products/admin_category.html.erb
- app/views/products/admin_index.html.erb
- config/initializers/assets.rb
> f_modified_product

- app/assets/stylesheets/users/show.scss
- app/views/cart_items/index.html.erb
- app/views/orders/new.html.erb
- app/views/orders/thanks.html.erb
- app/views/users/edit.html.erb
- app/views/users/show.html.erb
- config/initializers/assets.rb
下記の点を変更しました。
<変更点>
・ユーザー側　マイページ画面のCSSを追加
<対象ファイル>
・app/assets/stylesheets/users/show.scss
<備考>
マイページのフォントを使う場合は上記対象ファイルの@importの部分を追記すれば使えるようになります。font-weightで太さを変えます（100~700の７段階)
> Add_css_UserMyPage

- app/assets/stylesheets/greeds/new.scss
- app/controllers/products_controller.rb
- app/views/greeds/new.html.erb
- config/initializers/assets.rb
> F design new greed

- app/assets/stylesheets/cart_items/index.scss
- app/assets/stylesheets/orders/new.scss
- app/assets/stylesheets/products/index.scss
- app/assets/stylesheets/products/show.scss
- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/views/cart_items/index.html.erb
- app/views/orders/new.html.erb
- config/initializers/assets.rb
下記の点を変更しました。
<変更点>
① 商品画像ホバー時にゆっくりopacity効果
②「カートに入れる」ボタンのアニメーション
③ 決済確認画面のデザイン
④ 10点以上購入できていた不具合の修正
⑤ カート内に商品が入っていない時のビュー
> S design buy confirm

- app/assets/stylesheets/products/admin_edit.scss
- app/controllers/musics_controller.rb
- app/views/products/admin_edit.html.erb
- app/views/users/admin_edit.html.erb
- app/views/users/edit.html.erb
- config/initializers/assets.rb
- config/routes.rb
変更点
・商品編集ページのCSS
・住所追加のルート修正
確認お願いします。
> F design edit product

- app/assets/stylesheets/orders/new.scss
- app/assets/stylesheets/products/admin_show.scss
- app/views/products/admin_show.html.erb
- config/initializers/assets.rb
管理側商品詳細ページ
①リンクボタンの追加
②売上カラム追加
③ジャケット画像をテーブル内に格納
> modify_spacing

- app/assets/stylesheets/users/admin_show.scss
- app/controllers/addresses_controller.rb
- app/views/orders/admin_index.html.erb
- app/views/users/admin_edit.html.erb
- app/views/users/admin_index.html.erb
- app/views/users/admin_show.html.erb
- config/initializers/assets.rb
- config/routes.rb
> f_design_admin_show_user

- app/assets/stylesheets/products/index.scss
- app/assets/stylesheets/products/search.scss
- app/controllers/products_controller.rb
- app/views/orders/new.html.erb
- app/views/products/index.html.erb
- app/views/products/search.html.erb
- config/initializers/assets.rb
変更点
①商品一覧ぺージの画像大きさ調整、背景色設定
②商品検索結果画面のデザイン
③検索画面…カートに入れる機能追加
> S fix design products index

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
下記の点を変更しました。
<変更点>
①password再設定時のエラーを修正しました。
（進捗を考慮して、今回は再設定のパスワードが現在のパスワードと一緒でもOKにしています。）
②login,logout周りのエラーを修正しました。
　
<対象ファイル>
①app/controllers/users_controller.rb
②app/controllers/application_controller.rb
> Modified edit password

- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
ヘッダーを管理者/ユーザー(+未ログイン)で分けました。
・色：管理者…白、ユーザー…現在の色
> modify_admin-header

- app/assets/stylesheets/greeds/index.scss
- app/assets/stylesheets/users/contact.scss
- app/assets/stylesheets/users/payment.scss
- app/assets/stylesheets/users/privacy.scss
- app/assets/stylesheets/users/service.scss
下記の点を修正しました。
<変更点>
①footerコンテンツ内の文字色を修正
②欲選択画面の下部に空白が入らないよう修正
> T modified footer contents error

- app/assets/stylesheets/products/index.scss
- app/views/products/index.html.erb
- app/views/products/search.html.erb
変更点
・非ログイン時の検索結果エラー修正
・アイキャッチ画像修正
> S fix design#2

- app/assets/stylesheets/administrators/registrations/new.scss
- app/controllers/administrators_controller.rb
- app/views/administrators/registrations/new.html.erb
- app/views/orders/thanks.html.erb
下記の点を修正しました。
<修正点>
管理者側新規登録ページにおいて、管理者ログインしていないと新規登録できないよう修正しました。
> modified admin signup error
